version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/xingcan
    ports:
      - '27081:8081'
    container_name: wxcloud_xingcan
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=xingcan
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
networks:
  default:
    external:
      name: wxcb0
